Server:
  get:
    summary: Get all server settings with their current values
    operationId: getServerSettings
    tags:
      - Settings
    security:
      - tokenAuth: [ ]
    responses:
      200:
        description: Server settings
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: object
      default:
        description: Error
        content:
          application/json:
            schema:
              $ref: '../models/error.yaml#/Error'

User:
  get:
    summary: Get all user settings with the values for the current user
    operationId: getUserSettings
    tags:
      - Settings
    security:
      - tokenAuth: [ ]
    responses:
      200:
        description: User settings
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: object
      default:
        description: Error
        content:
          application/json:
            schema:
              $ref: '../models/error.yaml#/Error'

Update:
  put:
    summary: Update a server or user setting
    operationId: updateSetting
    tags:
      - Settings
    security:
      - tokenAuth: [ ]
    parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: string
    responses:
      200:
        description: Key and updated value
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: object
      default:
        description: Error
        content:
          application/json:
            schema:
              $ref: '../models/error.yaml#/Error'